[project]
name = "gfthings"
version = "0.9.0"
description = "Paul's Gridfinity Things"
authors = [
  {name = "Paul Bone", email = "paul@bone.id.au>"}
]
license = "CC-BY-NC-SA-4.0"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]
packages = [{include = "gfthings"}]
requires-python = ">=3.12,<3.13"
dependencies = [
    "build123d>=0.10,<0.11",

    # it's not a direct dependency but some later versions break with ocp.
    "ocp-gordon>=0.2,<0.3",
]

[project.urls]
Homepage = "https://github.com/PaulBone/gfthings"

[project.scripts]
gfpin = "gfthings.gfpin:main"
gfbin = "gfthings.gfbin:main"
gfbase = "gfthings.gfbase:main"
gfedge = "gfthings.gfedge:main"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]

[dependency-groups]
dev = [
    "ocp-vscode>=4.0.1",
    "pytest>=9.1.1",
]

